name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa à meia-noite todos os dias
  workflow_dispatch:  # Permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: israel-c-ribeiro  # Substitua pelo seu nome de usuário
          outputs: dist/snake.svg

      - name: Commit and Push SVG file
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git add dist/snake.svg
          git commit -m "Update snake SVG"
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
